#message when a player tries to connect to offline server
offline-message: '&cServer is offline!'

#time between pings/signupdate in seconds
interval: 5

#specify layouts here...
#%numpl% = online players
#%maxpl% = max players
#%motd% = motd
#%displayname% = displayname
#%isonline% whether the server is online or offline
layouts:
  #you can change the default layout but don't delete it!
  default:
    teleport: true
    layout:
      - 'Teleport to:'
      - '%motd%'
      - '%numpl%/%maxpl%'
      - '%isonline%'
    online: 'Online'
    offline: 'Offline'
  info:
    teleport: false
    layout:
      - '%displayname%'
      - '&c%numpl%&a/&c%maxpl%'
      - '&6infosign'
      - ''
    online: 'Online'
    offline: 'Offline'
  game:
    teleport: true
    layout:
      - '&nPvP-Match'
      - '%motd%'
      - '&1%numpl%&a/&1%maxpl%'
      - '%isonline%'
    online: '+++'
    offline: '---'
    
servers:
  pvp:
    address: '127.0.0.1:25566'
    displayname: '&cPVP'
  survival:
    address: '127.0.0.1:25567'
    displayname: '&aSurvival'