#message when a player tries to connect to offline server
offline-message: '&cServer is offline!'
#display name from config or motd

#specify layouts here...
#%numpl% = online players
#%maxpl% = max players
#%motd% = motd
#%displayname% = displayname specified in ping.yml
#%isonline% whether the server is online or offline
layouts:
  #don't delete the default layout!
  default:
    teleport: true
    layout:
      - 'Teleport to:'
      - '%motd%'
      - '%numpl%/%maxpl%'
      - '%isonline%'
    online: 'Online'
    offline: 'Offline'