name: ${project.name}
version: ${project.version}-b${BUILD_NUMBER}
description: ${project.description}
author: zh32

main: ${main.class}

database: true

permissions:
  teleportsigns.use:
    description: Use TeleportSigns
    default: true
  teleportsigns.create:
    description: Create TeleportSigns
    default: op
  teleportsigns.destroy:
    description: Destroy TeleportSigns
    default: op