name: ${project.name}
version: ${project.version}-b${BUILD_NUMBER}
description: ${project.description}
author: zh32

main: ${main.class}

database: true

permissions:
  lobby.teleport:
    description: Use TeleportSigns